#ifndef _DOCUMENTVIEW_H
#define _DOCUMENTVIEW_H
/*************************************/
/* DocumentView based on BView class */
/* Created : 9/2/2007 - 20:44:21     */
/* Code Generated by MeTOS           */
/*************************************/

#include "CTextView.h"


class DocumentView : public CTextView
{
public:
	// publics functions
	DocumentView(BRect frame,const char * name,uint32 resizeMask,uint32 flags);
//	virtual	void 	AttachedToWindow();
//	virtual	void 	DetachedFromWindow();
//	virtual	void 	AllAttached();
//	virtual	void 	AllDetached();
//	virtual	void 	MessageReceived(BMessage * msg);
	virtual	void 	Draw(BRect updateRect);
//	virtual	void 	MouseDown(BPoint where);
//	virtual	void 	MouseUp(BPoint where);
//	virtual	void 	MouseMoved(BPoint where,uint32 code,const BMessage * a_message);
//	virtual	void 	WindowActivated(bool state);
	virtual	void 	KeyDown(const char * bytes,int32 numBytes);
	virtual	void 	KeyUp(const char * bytes,int32 numBytes);
//	virtual	void 	FrameMoved(BPoint new_position);
	virtual	void 	FrameResized(float new_width,float new_height);
//	virtual	void 	TargetedByScrollView(BScrollView * scroll_view);

protected:
	// protected members

};

#endif
