/*************************************/
/* DocumentView based on BView class */
/* Created : 9/2/2007 - 20:44:21     */
/* Code Generated by MeTOS           */
/*************************************/

#include "DocumentView.h"


/***** Constructor ****/
DocumentView::DocumentView(BRect frame,const char *name,uint32 resizeMask,uint32 flags)
: CTextView(frame,name,BRect(frame.left+15,frame.top+15,frame.right-15,frame.bottom-15))
{
	// Allocate object


	// Adding object
}

///***** AttachedToWindow ****/
//void DocumentView::AttachedToWindow()
//{
//}
//
///***** DetachedFromWindow ****/
//void DocumentView::DetachedFromWindow()
//{
//}
//
///***** AllAttached ****/
//void DocumentView::AllAttached()
//{
//}
//
///***** AllDetached ****/
//void DocumentView::AllDetached()
//{
//}
//
///***** MessageReceived ****/
//void DocumentView::MessageReceived(BMessage *msg)
//{
//}
//
//const rgb_color Black =					{0,  0,  0,		255};
//const rgb_color White =					{255,  255,  255,		255};
//const rgb_color Grey  =					{200,  200,  200,		255};
//const rgb_color Red =					{255,  0,  0,		255 };
//const rgb_color Yellow =				{255,  255,  0,		255 };
//const rgb_color indigo =				{ 18,   82,156,     255 };
//
//
/***** Draw ****/
void DocumentView::Draw(BRect updateRect)
{


	
	CTextView::Draw(updateRect);
	
	StrokeRect( BRect( TextRect().left -2,
	                   TextRect().top -2,
	                   TextRect().right +2,
	                   TextRect().bottom +2 )
	          );
		
}

///***** MouseDown ****/
//void DocumentView::MouseDown(BPoint where)
//{
//}
//
///***** MouseUp ****/
//void DocumentView::MouseUp(BPoint where)
//{
//}
//
///***** MouseMoved ****/
//void DocumentView::MouseMoved(BPoint where,uint32 code,const BMessage *a_message)
//{
//}
//
///***** WindowActivated ****/
//void DocumentView::WindowActivated(bool state)
//{
//}
//
/***** KeyDown ****/
void DocumentView::KeyDown(const char *bytes,int32 numBytes)
{
	CTextView::KeyDown( bytes, numBytes);

	Invalidate();
}

/***** KeyUp ****/
void DocumentView::KeyUp(const char *bytes,int32 numBytes)
{
	CTextView::KeyUp( bytes, numBytes);
	Invalidate();
}
//
///***** FrameMoved ****/
//void DocumentView::FrameMoved(BPoint new_position)
//{
//}

/***** FrameResized ****/
void DocumentView::FrameResized(float new_width,float new_height)
{


    
}

///***** TargetedByScrollView ****/
//void DocumentView::TargetedByScrollView(BScrollView *scroll_view)
//{
//
//}
