#ifndef _OOFFICE_H
#define _OOFFICE_H
/***************************************/
/* OOffice based on BApplication class */
/* Created : 9/2/2007 - 20:44:21       */
/* Code Generated by MeTOS             */
/***************************************/

#include <Application.h>

class OOfficeWindow;

class OOffice : public BApplication
{
public:
	// publics functions
	OOffice();
	virtual void 	AboutRequested(void);

protected:
	// protected members
	OOfficeWindow		*_oofficewindow;

};

#endif
