#ifndef _WORKVIEW_H
#define _WORKVIEW_H
/*********************************/
/* WorkView based on BView class */
/* Created : 9/2/2007 - 20:44:21 */
/* Code Generated by MeTOS       */
/*********************************/

#include <ScrollView.h>
#include <TabView.h>

class BScrollBar;
class DocumentView;


class WorkView : public BView
{
public:
	// publics functions
	WorkView(BRect frame,const char * name,uint32 resizeMask,uint32 flags);
	virtual	void 	AttachedToWindow();
//	virtual	void 	AllAttached();
//	virtual	void 	DetachedFromWindow();
//	virtual	void 	AllDetached();
	virtual	void 	MessageReceived(BMessage * msg);
//	virtual	void 	Draw(BRect updateRect);
            void    SetZoom(float zoom);
            float   GetZoom() {
            	return _scale;
            }
//	virtual	void 	MouseDown(BPoint where);
//	virtual	void 	MouseUp(BPoint where);
//	virtual	void 	MouseMoved(BPoint where,uint32 code,const BMessage * a_message);
//	virtual	void 	WindowActivated(bool state);
//	virtual	void 	KeyDown(const char * bytes,int32 numBytes);
//	virtual	void 	KeyUp(const char * bytes,int32 numBytes);
//	virtual	void 	FrameResized(float new_width,float new_height);
//	virtual	void 	FrameMoved(BPoint new_position);
	virtual	void 	TargetedByScrollView(BScrollView * scroll_view);

	DocumentView		*_documentview;
	
protected:
	// protected members
	float _scale;

};

#endif
